import { TailwindIndicator } from "@lib/components/TailwindIndicatior";
import "./globals.css";
import { Footer,Navbar } from "@lib/components";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className="w-full">
        <Navbar />
        <main className="pt-20">{children}</main>

        <Footer />
        <TailwindIndicator />
      </body>
    </html>
  );
}
